<?php

function _dgf_visualisation_finale_access_callback() {
  global $user;
  //TODO sécurité à faire
  return $user->uid;
}

function _dgf_visualisation_finale_require_once_files() {
  require_once 'inc/synthese/synthese_form.inc';
  require_once 'inc/justificatif/justificatif_form.inc';
  require_once 'inc/justificatif_paiement/justificatif_paiement_form.inc';
  require_once'inc/justificatif_langs.inc';
  require_once'inc/justificatif_validate.inc';
}

function _dgf_visualisation_finale_include_js_css() {
  drupal_add_css(drupal_get_path('module', 'dgf_visualisation_finale' ) . '/css/dgf_visualisation_finale.css' );
  drupal_add_js(drupal_get_path('module', 'dgf_visualisation_finale' ) . '/js/dgf_visualisation_finale.js' );
}

function dgf_visualisation_finale_menu() {

  $items = array();
  $items['dgf/visualisation'] = array(
      'title' => t('Visualisation d\'un dossier'),
      'page callback' => 'dgf_visualisation_finale_view',
      'access callback' => '_dgf_visualisation_finale_access_callback',
      'type' => MENU_NORMAL_ITEM,
  );
  // Url pour supprimer un fichier dans justificatif
  $items['dgf/visualisation/%/sup/%/%'] = array(
      'page callback' => 'justificatifs_delete_files',
      'page arguments' => array(2,4,5),
      'access callback' => '_dgf_access_callback',
      'file' => 'inc/justificatif/justificatif_form.inc',
      'type' => MENU_CALLBACK,
  );
  // Url pour supprimer un fichier dans justificatif paiement
  $items['dgf/visualisation/%/supPaiement/%/%'] = array(
      'page callback' => 'justificatifs_paiement_delete_files',
      'page arguments' => array(2,4,5),
      'access callback' => '_dgf_access_callback',
      'file' => 'inc/justificatif_paiement/justificatif_paiement_form.inc',
      'type' => MENU_CALLBACK,
  );


  return $items;
}

function dgf_visualisation_finale_view() {
  global $user;
  _dgf_visualisation_finale_include_js_css();
  _dgf_visualisation_finale_require_once_files();

  $page = arg(3) ? arg(3) : 'synthese';

  $variables =  array(
      'page' => $page,
      'synthese' => dgf_visualisation_finale_synthese(),
      'justificatif'=> drupal_get_form('dgf_justificatif_form'),
      'justificatif_paiement' => drupal_get_form('dgf_justificatif_paiement_form'),
      'action_form' => drupal_get_form('dgf_visualisation_finale_form')
  );

  $output = theme('dgf_visualisation_finale_theme', $variables);
  return $output;
}

function dgf_visualisation_finale_form($form, &$form_state) {
  // Ajout des boutons d'actions

  dgf_boutons_action_form($form, array(''), array(''));

  return $form;
}
/*
 * Implementation of hook_theme().
*/

function dgf_visualisation_finale_theme($existing, $type, $theme, $path) {

  return array(

      'dgf_visualisation_finale_theme' => array(
          'template' => 'dgf_visualisation_finale',
          'path' => drupal_get_path('module', 'dgf_visualisation_finale') .'/theme',
      ),
      'dgf_visualisation_finale_synthese_theme' => array(
          'template' => 'dgf_visualisation_finale_synthese',
          'path' => drupal_get_path('module', 'dgf_visualisation_finale') .'/theme',
      ),
      'dgf_visualisation_finale_justificatif_theme' => array(
          'template' => 'dgf_visualisation_finale_justificatif',
          'path' => drupal_get_path('module', 'dgf_visualisation_finale') .'/theme',
      ),
      'dgf_visualisation_finale_justificatif_paiement_theme' => array(
          'template' => 'dgf_visualisation_finale_justificatif_paiement',
          'path' => drupal_get_path('module', 'dgf_visualisation_finale') .'/theme',
      ),
  );


}
