<?php

// define('DB_EXTRANET', 'opcaim_extranet');
// define('DB_SLAVE', 'opcaim_referentiel_esclave');

define('RAPPEL_DEMANDE_CONTRAT_PRO_STAGIAIRE', 'Attention : Pour être éligible au contrat de professionnalisation, le stagiaire de plus de 26 ans doit posséder un numéro d’identification « demandeur d’emploi », pour ce faire, il suffit de s\'inscrire au pôle emploi.');
define('ERR_STD_CONTRAT_COLLECTIVE_CONVENTION', 'Le champ Convention colective est obligatoire.');