<?php
/**
 * initialise le module hardis
 */
function hardis_bootstrap(){
    return array('stagiaires_list','voirstage_form','ajouterlieu_form','lieux_list','ajouterstage_form','stages_list','animateurs_list','ajouteranimateurs_form','inscrirestagiaire_form','dashbord_view','contenu_list','ajoutercontenu_form');
}
/**
 * Access callback
 * @return bool
 */
function _hardis_access_callback() {
  return user_access(3);
}
/**
 * Implements hook_menu().
 * @return array
 */
function hardis_menu() {
  $items = array();

    $items['stage_list'] = array(
        'title' => t('Liste des stages'),
        'page callback' => 'common_view',
        'page arguments' => array('list','stages'),
        'access callback' => '_hardis_access_callback',
        'file' => 'hardis_controller.inc',
        'type' => MENU_NORMAL_ITEM,
    );
  $items['dashbord'] = array(
    'title' => t('Liste des stages'),
    'page callback' => 'common_view',
    'page arguments' => array('view','dashbord'),
    'access callback' => '_hardis_access_callback',
    'file' => 'hardis_controller.inc',
    'type' => MENU_NORMAL_ITEM,
      'theme callback' => 'hardis_custom_theme',
  );
    $items['ajouterstage'] = array(
        'title' => t('Ajouter des stages'),
        'page callback' => 'common_view',
        'page arguments' => array('form','ajouterstage'),
        'access callback' => '_hardis_access_callback',
        'file' => 'hardis_controller.inc',
        'type' => MENU_NORMAL_ITEM,
    );
    $items['list_tarifs_form'] = array(
        'title' => t('Gestion des tarifs'),
        'page callback' => 'common_view',
        'page arguments' => array('list','tarifs'),
        'access callback' => '_hardis_access_callback',
        'file' => 'hardis_controller.inc',
        'type' => MENU_NORMAL_ITEM,
    );

    $items['stagiaires_list'] = array(
        'title' => t('Liste des stagiaires'),
        'page callback' => 'common_view',
        'page arguments' => array('list','stagiaires'),
        'access callback' => '_hardis_access_callback',
        'file' => 'hardis_controller.inc',
        'type' => MENU_NORMAL_ITEM,
    );

  $items['ajoutercontenu'] = array(
    'title' => t('Ajouter des stages'),
    'page callback' => 'common_view',
    'page arguments' => array('form','ajoutercontenu'),
    'access callback' => '_hardis_access_callback',
    'file' => 'hardis_controller.inc',
    'type' => MENU_NORMAL_ITEM,
  );
    $items['contenulist'] = array(
      'title' => t('Liste des cotenus'),
      'page callback' => 'common_view',
      'page arguments' => array('list','contenu'),
      'access callback' => '_hardis_access_callback',
      'file' => 'hardis_controller.inc',
      'type' => MENU_NORMAL_ITEM,
    );
    $items['prospects_list'] = array(
        'title' => t('Gestion des propects'),
        'page callback' => 'common_view',
        'page arguments' => array('list','prospects'),
        'access callback' => '_hardis_access_callback',
        'file' => 'hardis_controller.inc',
        'type' => MENU_NORMAL_ITEM,
    );
    $items['lieux_list'] = array(
        'title' => t('Gestion des lieux'),
        'page callback' => 'common_view',
        'page arguments' => array('list','lieux'),
        'access callback' => '_hardis_access_callback',
        'file' => 'hardis_controller.inc',
        'type' => MENU_NORMAL_ITEM,
    );
    $items['ajouterlieu'] = array(
        'title' => t('Ajouter un lieu'),
        'page callback' => 'common_view',
        'page arguments' => array('form','ajouterlieu'),
        'access callback' => '_hardis_access_callback',
        'file' => 'hardis_controller.inc',
        'type' => MENU_NORMAL_ITEM,
    );

    $items['dellieu'] = array(
      'title' => t('Ajouter un lieu'),
      'page callback' => 'common_callback',
      'page arguments' => array('call','delete_lieu'),
      'access callback' => '_hardis_access_callback',
      'file' => 'hardis_controller.inc',
      'type' => MENU_NORMAL_ITEM,
    );
    $items['delstage'] = array(
      'title' => t('Ajouter un lieu'),
      'page callback' => 'common_callback',
      'page arguments' => array('call','delete_stage'),
      'access callback' => '_hardis_access_callback',
      'file' => 'hardis_controller.inc',
      'type' => MENU_NORMAL_ITEM,
    );
    $items['delanimateur'] = array(
      'title' => t('Ajouter un lieu'),
      'page callback' => 'common_callback',
      'page arguments' => array('call','del_animateur'),
      'access callback' => '_hardis_access_callback',
      'file' => 'hardis_controller.inc',
      'type' => MENU_NORMAL_ITEM,
    );

    $items['animateurslist'] = array(
        'title' => t('Liste des animateurs'),
        'page callback' => 'common_view',
        'page arguments' => array('list','animateurs'),
        'access callback' => '_hardis_access_callback',
        'file' => 'hardis_controller.inc',
        'type' => MENU_NORMAL_ITEM,
    );

    $items['ajouteranimateur'] = array(
        'title' => t('Ajouter un animateur'),
        'page callback' => 'common_view',
        'page arguments' => array('form','ajouteranimateurs'),
        'access callback' => '_hardis_access_callback',
        'file' => 'hardis_controller.inc',
        'type' => MENU_NORMAL_ITEM,
    );
   $items['inscrirestagiaire'] = array(
     'title' => t('Ajouter un animateur'),
     'page callback' => 'common_view',
     'page arguments' => array('form','inscrirestagiaire'),
     'access callback' => '_hardis_access_callback',
     'file' => 'hardis_controller.inc',
     'type' => MENU_NORMAL_ITEM,
   );
    $items['voirstage'] = array(
        'title' => t('Voir un stage'),
        'page callback' => 'common_view',
        'page arguments' => array('form','voirstage'),
        'access callback' => '_hardis_access_callback',
        'file' => 'hardis_controller.inc',
        'type' => MENU_NORMAL_ITEM,
    );




    return $items;
}
/**
 * Implement hook_theme
 * @param $existing
 * @param $type
 * @param $theme
 * @param $path
 * @return array
 */
function hardis_theme($existing, $type, $theme, $path)
{
    foreach (hardis_bootstrap() as $value) {
        $aReturn[$value] = array(
            'variables' => array(),
            'render element' => 'element',
            'template' => $value,

            'path' => drupal_get_path('module', 'hardis') . '/theme',
        );
    }
    return $aReturn;
}
function hardis_custom_theme() {
    // Allow the user to request a particular theme via a query parameter.
        return 'opcaim';
}
