<?php

function _dgf_suivi_demande_access_callback() {
  return shared_user_access('GES_CP') ;
}

function _dgf_suivi_paiement_access_callback() {
    return shared_user_access('GES_CP') ;
}

/**
 * Implements hook_menu().
 */
function dgf_suivi_menu() {
  $items = array();
  // Pour la parti suivi des demandes 
  dgf_menu_suivi_demande($items);
    
  return $items;
}

/**
 * 
 * @param unknown $existing
 * @param unknown $type
 * @param unknown $theme
 * @param unknown $path
 * @return theme drupal suivi demande
 */
function dgf_suivi_theme($existing, $type, $theme, $path) {
  $theme_array = array(
      // Template général pour afficher la liste des demandes
      'dgf_suivi_demande_liste_page_theme' => array(
          'template' => 'suivi_demande_liste_page',
          'path' => drupal_get_path('module', 'dgf_suivi') .'/inc/demande/theme',
      ),
  );

  return $theme_array;
}

function dgf_menu_suivi_demande(&$items) {
  $items['suivi/demande'] = array(
      'title' => t('Suivi des demandes de gestion et financement'),
      'page callback' => 'dgf_suivi_demande_list_page',
      'access callback' => '_dgf_suivi_demande_access_callback',
      'file' => 'inc/demande/suivi_demande_controller.inc',
      'type' => MENU_NORMAL_ITEM,
      'access arguments' => array('_dgf_suivi_demande_access_callback'),
  );

  $items['get/suivi/demande/liste-etablissement'] = array(
      'title' => t('Liste des établissements'),
      'page callback' => 'dgf_suivi_demande_get_list_etablishment',
      'access callback' => '_dgf_suivi_demande_access_callback',
      'file' => 'inc/demande/suivi_demande_db.inc',
      'type' => MENU_CALLBACK,
  );

  $items['get/suivi/demande/liste-participant'] = array(
      'title' => t('Nombre de participants à la formation'),
      'page callback' => 'dgf_suivi_demande_get_list_intern',
      'access callback' => '_dgf_suivi_demande_access_callback',
      'file' => 'inc/demande/suivi_demande_db.inc',
      'type' => MENU_CALLBACK,
  );
  
  $items['get/suivi/demande/justificatifs'] = array(
      'title' => t('Justificatifs de la demande'),
      'page callback' => 'dgf_suivi_demande_get_justifs',
      'access callback' => '_dgf_suivi_demande_access_callback',
      'file' => 'inc/demande/suivi_demande_db.inc',
      'type' => MENU_CALLBACK,
  );
  
  $items['delete/suivi/demande'] = array(
      'title' => t('Suppression de la demande'),
      'page callback' => 'dgf_suivi_demande_delete',
      'access callback' => '_dgf_suivi_demande_access_callback',
      'file' => 'inc/demande/suivi_demande_db.inc',
      'type' => MENU_CALLBACK,
  );
  
  $items['dgf/duplication'] = array(
      'title' => t('Duplication de la demande'),
      'page callback' => 'dgf_demande_duplicate',
      'access callback' => '_dgf_suivi_demande_access_callback',
      'file' => 'inc/demande/suivi_demande_controller.inc',
      'type' => MENU_CALLBACK,
  );

  $items['suivi/demande/export'] = array(
      'title' => t('Export CSV des demandes'),
      'page callback' => 'dgf_demande_export',
      'access callback' => TRUE,
      'file' => 'inc/demande/suivi_demande_export.inc',
      'type' => MENU_CALLBACK,
  );
}

