<?php

// Defines.
define('LOGIN_MODULE_PATH', drupal_get_path('module', 'login'));

function login_menu() {
  $items = array();
  $items['login'] = array(
      'title' => t('Se connecter'),
      'page callback' => 'login_view',
      'access callback' => true,
      'type' => MENU_CALLBACK,
  );

  $items['login/modalSubmit'] = array(
      'title' => t('submit'),
      'page callback' => 'password_forgot',
      'file' => 'login_form_submit.inc',
      'access callback' => true,
      'type' => MENU_CALLBACK,
  );

  return $items;
}


function login_reset_password_custom_validate($form, &$form_state) {
  element_shared_password_validate($form['account']['pass'], $form_state);
}

function login_reset_password_custom_submit($form, &$form_state) {
  global $user;
  $edit = array('pass' => $form_state['values']['pass']);
  $account = user_save($form['#user'], $edit);
  session_destroy();
  drupal_set_message('Votre mot de passe a bien été modifié');
  drupal_goto('mote-passe.php');
}






function login_view() {
  global $user;

  require_once 'login_langs.inc';
  require_once 'login_form.inc';
  require_once 'login_form_submit.inc';
  require_once 'login_db.inc';

  // Si l'utilisateur est déjà connecté, il est redirigé vers sa page d'accueil
  if ($user->uid != 0) {
    drupal_goto('dashboard');
  }


$form = drupal_get_form('login_form');

  $variables =  array(
    'login_form' => $form,
    'login_password_forgot_form' => drupal_get_form('login_password_forgot_form'),
//     'login_follow_form' => drupal_get_form('login_follow_form')
  );

  $output = theme('custom_login', $variables);

  return $output;
}




