<?php

// Defines.
define('LOGIN_MODULE_PATH', drupal_get_path('module', 'login'));

function login_menu() {
  $items = array();
  $items['login'] = array(
      'title' => t('Se connecter'),
      'page callback' => 'login_view',
      'access callback' => true,
      'type' => MENU_CALLBACK,
  );
  return $items;
}


function login_view() {
  global $user;

  require_once 'login_langs.inc';
  require_once 'login_form.inc';
  require_once 'login_form_submit.inc';
  require_once 'login_db.inc';

  // Si l'utilisateur est déjà connecté, il est redirigé vers sa page d'accueil
  if ($user->uid != 0) {
    drupal_goto('dashboard');
  }


$form = drupal_get_form('login_form');

  $variables =  array(
    'login_form' => $form
  );

  $output = theme('custom_login', $variables);

  return $output;
}




